api = "0.8"

[buildpack]
id = "bash-examples/git-revision"
name = "Buildpack for git revision"
version = "1.0.0"
[[buildpack.licenses]]
type = "MIT"

[metadata]
include-files = ["bin/detect", "bin/build", "bin/buildpack.sh", "bin/dasel", "buildpack.toml"]
[[metadata.dependencies]]
stacks = ["io.buildpacks.stacks.jammy"]

[[stacks]]
id = "*"

[[targets]]
os = "linux"
[[targets.distros]]
name = "ubuntu"
